# Generated by Django 3.0.5 on 2020-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instragram URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
