# Generated by Django 3.0.5 on 2020-04-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200420_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fontawesome', models.CharField(max_length=30)),
                ('technical', models.BooleanField(verbose_name='Technical skill?')),
                ('personal', models.BooleanField(verbose_name='Personal skill?')),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('resume', models.TextField()),
                ('company', models.CharField(max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('resume', models.TextField()),
                ('institute', models.CharField(max_length=30)),
                ('level', models.IntegerField(verbose_name='Bachelor level')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
