# Generated by Django 3.0.5 on 2020-04-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_formation_professional_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='persons',
            field=models.ManyToManyField(to='about.Person'),
        ),
    ]
