# Generated by Django 3.0.5 on 2020-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_skill_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='visible',
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='about.Skill'),
        ),
    ]
