# Generated by Django 3.0.5 on 2020-04-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20200422_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillSet',
        ),
        migrations.RemoveField(
            model_name='person',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.Person'),
        ),
    ]
