# Generated by Django 3.0.5 on 2020-04-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20200422_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Person'),
        ),
    ]
