# Generated by Django 3.0.5 on 2020-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20200423_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
