# Generated by Django 3.0.5 on 2020-04-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_skill_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='codingame',
            field=models.URLField(blank=True, null=True, verbose_name='Codingame URL'),
        ),
    ]
