# Generated by Django 3.0.5 on 2020-04-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_person_codingame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='skill',
            name='fontawesome',
            field=models.CharField(max_length=60),
        ),
    ]
